connection: &connection
  adapter: mysql2
  encoding: utf8mb4
  socket: /tmp/mysql.sock

config: &config
  primary:
    <<: *connection
    database: <%= Rails.application.credentials.dig(:db, :primary, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :primary, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :primary, :password) %>
    host: <%= Rails.application.credentials.dig(:db, :primary, :host) %>
    port: <%= Rails.application.credentials.dig(:db, :primary, :port) %>
  legacy:
    <<: *connection
    database_tasks: false
    database: <%= Rails.application.credentials.dig(:db, :legacy, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :legacy, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :legacy, :password) %>
    host: <%= Rails.application.credentials.dig(:db, :legacy, :host) %>
    port: <%= Rails.application.credentials.dig(:db, :legacy, :port) %>

development:
  <<: *config

test:
  <<: *config

staging:
  <<: *config

production:
  <<: *config
