mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  socket: /tmp/mysql.sock

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

main_db: &main_db
  <<: *mysql
  username: <%= Rails.application.credentials.dig(:db, :primary, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :primary, :password) %>
  host:     <%= Rails.application.credentials.dig(:db, :primary, :host) %>
  port:     <%= Rails.application.credentials.dig(:db, :primary, :port) %>

config: &config
  primary:
    <<: *main_db
    database: <%= Rails.application.credentials.dig(:db, :primary, :database) %>
  legacy:
    <<: *mysql
    database_tasks: false
    database: <%= Rails.application.credentials.dig(:db, :legacy, :database) %>
    username: <%= Rails.application.credentials.dig(:db, :legacy, :username) %>
    password: <%= Rails.application.credentials.dig(:db, :legacy, :password) %>
    host:     <%= Rails.application.credentials.dig(:db, :legacy, :host) %>
    port:     <%= Rails.application.credentials.dig(:db, :legacy, :port) %>

development:
  <<: *config

  cache:
    <<: *sqlite
    database:         oho_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *sqlite
    database:         /tmp/solid_queue.sqlite
    migrations_paths: db/queue_migrate

  cable:
    <<: *sqlite
    database:         /tmp/solid_cable.sqlite
    migrations_paths: db/cable_migrate

test:
  <<: *config

staging:
  <<: *config

production:
  <<: *config

  queue:
    <<: *sqlite
    database:         <%= ENV["SOLID_ROOT"]%>/oho_solid_queue.sqlite
    migrations_paths: db/queue_migrate

  cable:
    <<: *sqlite
    database:         <%= ENV["SOLID_ROOT"]%>/oho_solid_cable.sqlite
    migrations_paths: db/cable_migrate

  cache:
    <<: *sqlite
    database:         <%= ENV["SOLID_ROOT"]%>/oho_solid_cache.sqlite
    migrations_paths: db/cache_migrate
